#!/bin/bash

numFile=$HOME/Pictures/asciiArt/randomise/lastNum
declare -i num=$(cat $numFile)
limit=5

((num = num+1))
if [ $num -gt $limit ]
then
	num=1
fi

imgFile=/home/liviu/Pictures/asciiArt/randomise/rand.$num

# Print ascii art
neofetch --ascii $imgFile --ascii_colors 1

echo $num > $numFile
