[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#a89984"
yellow = "#fabd2f"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 12

[font.bold]
family = "ProFontIIxNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "ProFontIIxNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "ProFontIIxNerdFontMono"
style = "Italic"

[font.normal]
family = "ProFontIIxNerdFontMono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"
